const target_materials = [
  "Cement",
  "Clay, Ceramic, Refractory Mnls.",
  "Common Clays NEC",
  "Common Shale",
  "Construction Sand and Gravel",
  "Crushed, Broken Basalt",
  "Crushed, Broken Granite",
  "Crushed, Broken Limestone NEC",
  "Crushed, Broken Marble",
  "Crushed, Broken Mica",
  "Crushed, Broken Quartzite",
  "Crushed, Broken Sandstone",
  "Crushed, Broken Slate",
  "Crushed, Broken Stone NEC",
  "Crushed, Broken Traprock",
  "Dimension Basalt",
  "Dimension Granite",
  "Dimension Limestone",
  "Dimension Marble",
  "Dimension Mica",
  "Dimension Quartzite",
  "Dimension Sandstone",
  "Dimension Slate",
  "Dimension Stone NEC",
  "Dimension Traprock",
  "Lime",
  "Nonmetal",
  "Sand, Common",
  "Sand, Industrial NEC",
];
