all_colnames = [
    "LeaseNumber",
    "County",
    "Township",
    "Range",
    "Section",
    "LegalDescription",
    "CommodityDescription",
    "FirstName",
    "LastName",
    "EntityName",
    "PrimaryAddress",
    "City",
    "State",
    "ZIPCode",
    "First Name",
    "Last Name",
    "Combined Name",
    "Office",
    "Program",
    "Phone\xa0",
    "username",
    "Email",
    "Permit number (ID)",
    "Permittee (Operator)",
    "Site name",
    "Latitude",
    "Longitude",
    "County Name",
    "Range",
    "Section",
    "Township",
    "Qtr-qtr",
    "Qtr",
    "Correspondence(PR) Company Name",
    "Correspondence(PR) Contact First Name",
    "Correspondence(PR) Contact Last Name",
    "Correspondence Telephone Number",
    "Correspondence(PR) Address 1",
    "Correspondence(PR) Address 2",
    "Correspondence(PR) City",
    "Correspondence(PR) State",
    "Correspondence(PR) Zip Code",
    "Commodity",
    "Permit Type",
    "PERMIT #",
    "COMPANY NAME",
    "COUNTY",
    "TOWNSHIP",
    "ISSUANCE DATE",
    "MINERAL(S) MINED",
    "STREET ADDRESS",
    "CITY",
    "STATE",
    "ZIP",
    "PHONE NUMBER",
    "LATITUDE",
    "LONGITUDE",
    "Unnamed: 0",
    "Unnamed: 1",
    "Unnamed: 2",
    "Unnamed: 3",
    "Unnamed: 4",
    "Unnamed: 5",
    "Unnamed: 6",
    "Unnamed: 7",
    "Unnamed: 8",
    "Unnamed: 9",
    "Unnamed: 10",
    "Unnamed: 11",
    "Unnamed: 12",
    "Unnamed: 13",
    "Unnamed: 14",
    "Unnamed: 15",
    "Unnamed: 16",
    "Unnamed: 17",
    "COMPANY",
    "LICENSE",
    "TITLE",
    "FIRST",
    "LAST",
    "STREET",
    "CITY",
    "STATE",
    "ZIP",
    "E-mail",
    "PHONE",
    "FAX",
    "LICSTAT",
    "OBJECTID",
    "Mine_ID",
    "Mine Name",
    "Operation Type",
    "Mine Status",
    "Primary Product",
    "Other Products",
    "Owner",
    "Operator",
    "Lead Agency",
    "Report Year",
    "Acres Disturbed",
    "Reclamation Status",
    "Permit Number",
    "Permit Acres",
    "Financial Assurance Mechanism Total",
    "Financial Assurance Cost Estimate",
    "Latitude",
    "Longitude",
    "x",
    "y",
    "Mine ID",
    "REPORT_YEAR",
    "CONTACT_EMAIL",
    "CONTACT_FIRST",
    "CONTACT_LAST",
    "CONTACT_PHONE",
    "MINE_ADDRESS",
    "MINE_CITY",
    "MINE_STATE",
    "MINE_ZIP",
    "Lead Agency",
    "Permit No",
    "Site Name",
    "Permittee Name",
    "Project Name",
    "Permit Type",
    "Status",
    "Rating",
    "Location",
    "City",
    "County",
    "EFO Name",
    "__Issuance__",
    "_Effective_",
    "__Expiration__",
    "OBJECTID",
    "SITE_ID",
    "SITE_NAME",
    "BOUNDARY",
    "MARKET_RESOURCE",
    "FL_REC_RULE",
    "PERMIT_AGENCY",
    "DATE_ENTERED",
    "DIGITIZER",
    "SORT_GRADE",
    "MINING_BEGAN",
    "MITIGATION_REQD",
    "NONMAN_AREAS",
    "SHEER_WALLS",
    "RuleID",
    "DOCUMENT_LINK",
    "Shape_Length",
    "Shape_Area",
    "CENTROID_X",
    "CENTROID_Y",
    "AI_ID",
    "FACILITY_NAME",
    "ACTIVITY_NO",
    "PERMIT_NO",
    "PHYSICAL_ADDRESS",
    "LATITUDE",
    "LONGITUDE",
    "SIC_CODE",
    "SIC_DESC",
    "MAILING_ADDRESS",
    "WTR_PMT_CONTACT",
    "WPC_PHONE",
    "WPC_EMAIL",
    "ORG_OPERATOR",
    "ORG_OP_PHONE",
    "PERSON_OPERATOR",
    "PERSON_OP_PHONE",
    "PERSON_OP_EMAIL",
    "FACILITY_NAME",
    "LATITUDE",
    "LONGITUDE",
    "Company",
    "City",
    "Contact Person",
    "County",
    "Cur Range",
    "Cur Section",
    "Cur Township",
    "Current Location",
    "Driving Instruction",
    "E-Mail",
    "Elevation",
    "FAX",
    "GPS",
    "lat",
    "Long",
    "Mail Address",
    "Mine•Plant Name",
    "Phone",
    "Product",
    "State",
    "Type",
    "UTM",
    "Zip",
    "County",
    "Company",
    "City",
    "Latitude",
    "Longitude",
    "Mine/Plant Name",
    "Type",
    "Product",
    "Commodity Type",
    "Commodity Family",
    "Asphalt Hot Plant?",
    "Concrete Batch Plant?",
    "NPDES ID",
    "Permit Name",
    "State Facility ID",
    "Mjr",
    "Facility Type Desc",
    "Facility Type Indicator",
    "Permit Type Desc",
    "Permit Status Desc",
    "Issue Date",
    "Effective Date",
    "Expiration Date",
    "Termination Date",
    "Latitude in Decimal Degrees",
    "Longitude in Decimal Degrees",
    "Location Address",
    "City",
    "Facility Location Info..State Code",
    "Zip",
    "County Name",
    "Primary Facility SIC Code",
    "Primary Facility SIC Desc",
    "Permit SIC",
    "Permit SIC Description",
    "FRS HUC Code",
    "HUC Code",
    "State Water Body Name",
    "State Water Body",
    "Total Actual Average Flow (MGD)",
    "Total App. Design Flow (MGD)",
    "FIPS City Code",
    "FIPS County Code",
    "State-Region",
    "Congressional District Number",
    "Legislative District Number",
    "Name",
    "First",
    "Title",
    "Phone",
    "Email",
    "COUNTY        ",
    "COMPANY NAME                  ",
    "MINE NAME/NUMBER    ",
    "PERMIT ",
    "COMMODITY",
    "PERMITTED ACRES",
    "DISTURBED ACRES",
    "ACRES RECLAIMED THIS YR",
    "ORG PERMIT",
    "Name",
    "PermitNumber",
    "FacilityName",
    "Facility Address",
    "Facility SupAddress",
    "City",
    "State",
    "Zip",
    "COMPANY NAME",
    "CONTACT NAME",
    "PHONE",
    "EMAIL",
    "LICENSE #",
    "SITES_NO",
    "SITES_NAME",
    "SITES COUNTY",
    "SITES_Q1",
    "SITES_Q2",
    "SITES_SECTION",
    "SITES_TOWNSHIP",
    "SITES_RANGE",
    "SITES_RANGEDIR",
    "LICENSE TYPE",
    "CALICHE TONNS",
    "CLAY TONNS",
    "GRAVELDREDGE TONNS ",
    "GRAVELSURFACE TONNS ($0)",
    "GYPSUM TONNS  ",
    "LANDFILL TONNS  ",
    "LIMESTONE TONNS ",
    "OTHER TONNS",
    "QUARTZITE TONNS ",
    "ROCK TONNS",
    "SALT TONNS",
    "SANDSURFACE TONNS",
    "SANDDREDGE TONNS",
    "SHALE TONNS",
    "SOIL TONNS",
    "STONE TONNS",
    "TOPSOIL TONNS",
    "VOLCANICASH TONNS",
    "key",
    "Facility ID",
    "ICIS ID",
    "Facility Name",
    "SIC Code",
    "Inspector",
    "Classification",
    "Owner Name",
    "Owner Mailing Address",
    "Facility Physical Address1",
    "Facility Physical Address2",
    "Facility Physical City",
    "Facility Physical State",
    "Facility Physical Zip",
    "Operating",
    "Full PTE",
    "File",
    "Control Region",
    "Responsible Officials",
    "Responsible Officials_Email",
    "Sanctioned",
    "Lat",
    "Long",
    "Pending or Active Permits",
    "Key",
    "Permit ID",
    "Application/Permit",
    "Legal (Prior) ID",
    "Revision Number",
    "Revision Type",
    "Project Name",
    "Project Classifications",
    "Permit Type",
    "Facility ID",
    "Facility Owner",
    "Facility Name",
    "Received Date",
    "Received Complete Date",
    "Issue Date",
    "Total Elapsed Days",
    "Hold Days",
    "Net Elapsed Days",
    "Hold Ongoing",
    "Effective Date",
    "Expire Date",
    "Permit Status",
    "Engineer",
    "Begin Work",
    "Draft Deliver to Super",
    "Start Public Notice",
    "End Public Notice",
    "Final Deliver to Super",
    "Transmit to EPA",
    "Facility Inspector",
    "Phase Code",
    "Sanctioned?",
    "CWPName",
    "SourceID",
    "CWPStreet",
    "CWPCity",
    "CWPState",
    "RegistryID",
    "CWPSICCodes",
    "CWPNAICSCodes",
    "FacLat",
    "FacLong",
    "CWPFacilityTypeCode",
    "FacMapFlg",
    "DFR URL",
    "Site ID",
    "Name",
    "Manager",
    "Classification",
    "Status",
    "Permit Status",
    "Region",
    "Permit",
    "Site / Facility",
    "City",
    "Owner / Operator",
    "Date Issued",
    "Primary SIC/NAICS code",
    "Seconday SIC/NAICS code",
    "GPS Latitude",
    "GPS Longitude",
    "Facility Physical Address",
    "Facility Physical Description",
    "Borough (or similar governemtn subdivision)",
    "Phone number",
    "email address",
    "Company Name",
    "Quarry/Mine Name",
    "Legal Description",
    "County",
    "Permit No",
    "Product",
    "Contact Company",
    "Contact Address",
    "Contact Name",
    "Phone Number",
    "Cell",
    "Category",
    "Permit Number",
    "Company",
    "Company Address",
    "Local Address",
    "Contact Name",
    "Contact Number",
    "Email Address",
    "Type of Operation",
    "Permit Code",
    "Description",
    "5,000CY &/or 1-acre Limit per 12-month Period",
    "NO Extraction Limit",
    "Reclamation Plan Required",
    "Reclamation Security Required",
    "NOTE: DOGAMI permits are renewed annually on a rotating schedule. Surface mining renewals include reported production for the previous 12-month period. For example, sites that renew in December 2018 report production from December 2017 through November 2018.  Therefore our final 2017 production numbers are not available until after all the 2018 renewals have been processed. This usually occurs by mid-spring. If the entry in the state-wide row is labeled incomplete, that means our records show that not all renewals for that year have been processed and the total production numbers are not yet finalized.",
    "PermitID",
    "Permit Type",
    "Status",
    "Site Name",
    "Permittee",
    "Department",
    "Address1",
    "Address2",
    "City",
    "State",
    "Zip",
    "Country",
    "Landowner",
    "Commodity",
    "County",
    "TRS TL",
    "Latitude",
    "Longitude",
    "Site Address",
    "DEQ Permit",
    "DEQ Status",
    "DEQ_FileNo",
    "GoogleMapsLink",
    "Permit#",
    "Permit Year",
    "Amendment/Expansion",
    "Status",
    "PermiteeName",
    "CountyCode",
    "CountyName",
    "Phone",
    "Fax",
    "Email",
    "Address1",
    "Address2",
    "City",
    "State",
    "Zip",
    "PermitType",
    "FeesPaid",
    "GRFees",
    "Credit",
    "ApplicationDate",
    "IssuanceDate",
    "ExpirationDate",
    "EffectiveDate",
    "OperatorNames",
    "Inspector",
    "AreaNumber",
    "Comments",
    "KeyIdImHead",
    "PERMIT_NUMBER",
    "Permittee_Bus_Name",
    "LOCATION_NAME",
    "FIPS_COUNTY_DESC",
    "REGION_NAME",
    "River_Basin_Name",
    "ORIG_ISSUE_DATE",
    "EXPIRATION_DATE",
    "Select Contact Person",
    "Select Addr, City, State, Zip",
    "Phone",
    "ORIGINAL_APP_RECEIVED_DATE",
    "HEARING_DATE",
    "DATE_DENIED",
    "PERMIT_REVISION_DATE",
    "RELEASE_DATE",
    "MINE_STATUS",
    "COMMODITY_CODE",
    "TOTAL_ACRES_PERMITTED",
    "BONDED_ACRES",
    "BOND_TYPE_CODE",
    "ARR_RECEIVED_DATE",
    "BOND_AMOUNT",
    "QUADRANGLE_NAME",
    "LATITUDE_MEASURE",
    "LONGITUDE_MEASURE",
    "CALENDAR_YEAR",
    "NEW_ACRES_AFFECTED_TOTAL",
    "NEW_ACRES_RECLAIMED",
    "ACRES_CURRENT_TOTAL",
    "LAST_UPDATE_DATE",
    "INSPECTED_BY",
    "LAST_NOD_DATE",
    "LAST_NOV_DATE",
    "Last_Inspection_Date",
    "NEXT_SCHEDULED_INSPECTION_DATE",
    "Unnamed: 0",
    "PERMIT #",
    "COMPANY NAME & ADDRESS",
    "#",
    "CASH",
    "SURETY ",
    "Unnamed: 6",
    "NEGOT. ",
    "Unnamed: 8",
    "BOND",
    "PERMIT ",
    "ACREAGE",
    "COUNTY",
    "SECTION",
    "TOWN-",
    "RANGE",
    "ACCESS TO MINE SITES",
    "Material 1 Code",
    "Permit ID",
    "Mine Name",
    "Owner Name",
    "Contacts",
    "Permitted Acres",
    "Site County",
    "Longitude",
    "Latitude",
    "Ute North",
    "Ute East",
    "Map ID",
    "Billing Address",
    "Billing CSZ",
    "Company EMail",
    "I-002131",
    "CALHOUN MINE",
    "HAIR & SONS INC",
    "CALHOUN",
    "SAND",
    "SANDCLAY",
    "-80.88516638",
    33.63659272,
    "no record",
    "SicPrimary",
    "Desc1",
    "TownCode",
    "Premise",
    "EMIT Reporting Period",
    "SiteName",
    "AddressLine1",
    "AddressLine2",
    "City",
    "ZipCode",
    "Zip4",
    "AFINDash",
    "PmtNbr",
    "AFIN",
    "LINK",
    "FacName",
    "Decimal Latitude",
    "Decimal Longitude",
    "FacSiteCity",
    "FacCounty",
    "FacCountyName",
    "FacPrimarySICCode",
    "FacPrimarySICDesc",
    "FacSecondarySICCode",
    "FacSecondarySICDesc",
    "FacTertiarySICCode",
    "FacTertiarySICDesc",
    "FacPrimaryNAICSCode",
    "FacPrimaryNAICSDesc",
    "FacSecondaryNAICSCode",
    "FacSecondaryNAICSDesc",
    "FacTertiaryNAICSCode",
    "FacTertiaryNAICSDesc",
    "PermitteeNameAddress",
    "PmtMedia",
    "MediaDesc",
    "PmtType",
    "PmtTypeDesc",
    "PmtStatus",
    "PmtStatusDesc",
    "MediaPlusPmtTypeCode",
    "PmtPDFOnline",
    "PmtPDFOnlineDIR",
    "Registration Number",
    "Regulated Entity Reference Number ",
    "Facility Type",
    "Facility Name",
    "Address",
    "City",
    "State",
    "Zip",
    "County",
    "TCEQ Region",
    "Registration Date",
    "Phone",
    "PERMIT_NO",
    "DATE_COVERAGE_BEGAN",
    "CN",
    "PERMITTEE_NAME",
    "RN",
    "SITE_NAME",
    "COUNTY",
    "TCEQ_REGION",
    "SITE_ADDRESS",
    "SITE_PHYS_LOC_DESC",
    "SITE_NEAR_CITY_NAME",
    "SITE_NEAR_ZIP",
    "PRIMARY_SIC_CODE",
    "SECONDARY_SIC_CODE",
    "SECTOR",
    "ACTIVITY_CODE",
    "AI",
    "RN",
    "AUTH TYPE",
    "APPROVAL DATE",
    "ORIGINAL APPROVAL DATE",
    "EXPIRATION DATE",
    "AUTH STATUS",
    "TPDES/STATE",
    "EPA ID",
    "EPA FAC CLASS",
    "CN",
    "PERMITTEE NAME(S)",
    "PERMITTEE ADDRESS(S)",
    "FACILITY COUNTY",
    "REGION",
    "SECONDARY COUNTY",
    "SECONDARY REGION",
    "AI SITE NAME",
    "SITE LOCATION",
    "LATTITUDE",
    "LONGITUDE",
    "PERMIT AUTHORITY",
    "COMPLIANCE AUTHORITY",
    "FACILITY OPERATIONAL STATUS",
    "FACILITY DISPOSAL METHOD",
    "PRETREATMENT FACILITY DESIGNATION",
    "FACILITY TOXIC RATING",
    "FACILITY AVG DESIGN FLOW",
    "LOCATED IN COASTAL ZONE",
    "INSTITUTE OF HIGHER LEARNING",
    "BIO-ENERGY FACILITY",
    "TREATMENT COMPONENT",
    "PRIMARY SIC CODE",
    "SECONDARY SIC CODE",
    "PRIMARY NAICS CODE",
    "SECONDARY NAICS CODE",
    "SEGMENT",
    "BASIN",
    "ANIMAL TYPE & HEAD COUNT",
    "FACILITY CHARACTERISTICS ID",
    "PERMIT_NO",
    "DATE_COVERAGE_BEGAN",
    "CN",
    "PERMITTEE_NAME",
    "RN",
    "SITE_NAME",
    "COUNTY",
    "TCEQ_REGION",
    "SITE_ADDRESS",
    "SITE_PHYS_LOC_DESC",
    "SITE_NEAR_CITY_NAME",
    "SITE_NEAR_ZIP",
    "PRIMARY_SIC_CODE",
    "SECONDARY_SIC_CODE",
    "AREA_DISTURBED",
    "SEGMENT_NUMBER",
    "RECEIVING_WATER_BODY",
    "PERMIT_NO",
    "DATE_COVERAGE_BEGAN",
    "CN",
    "PERMITTEE_NAME",
    "RN",
    "SITE_NAME",
    "COUNTY",
    "TCEQ_REGION",
    "SITE_ADDRESS",
    "SITE_PHYS_LOC_DESC",
    "SITE_NEAR_CITY_NAME",
    "SITE_NEAR_ZIP",
    "PRIMARY_SIC_CODE",
    "SECONDARY_SIC_CODE",
    "SECTOR",
    "ACTIVITY_CODE",
    "Supplier",
    "Code",
    "Permit",
    "Link",
    "Program",
    "Site Name",
    "Additional ID",
    "Physical Type",
    "Legal Status",
    "Legal Status Date",
    "Physical Site Status",
    "RN",
    "County",
    "Region",
    "Phys Addr Line 1",
    "Phys Addr Line 2",
    "Phys Addr City",
    "Phys Addr State",
    "Phys Addr Zip",
    "Phys Addr Zip+4",
    "Near Phys Loc Txt",
    "Near Phys Loc City",
    "Near Phys Loc State",
    "Near Phys Loc Zip",
    "Latitude",
    "Longitude",
    "PERMIT_NO",
    "DATE_COVERAGE_BEGAN",
    "MOST_RECENT_REGISTRATION_DT",
    "ISSUE_TO_CN",
    "ISSUE_TO_NAME",
    "RN",
    "RE_NAME",
    "SITE_NAME",
    "COUNTY",
    "TCEQ_REGION",
    "SITE_LATITUDE",
    "SITE_LONGITUDE",
    "SITE_ADDRESS_LABEL",
    "SITE_PHYS_LOC_DESC",
    "SITE_NEAR_CITY_NAME",
    "SITE_NEAR_ZIP",
    "CONTACT FIRST NAME",
    "CONTACT LAST NAME",
    "CONTACT ORGANIZATION",
    "CONTACT_MAILING_ADDRESS",
    "PHONE",
    "no record",
    "PRIMARY_SIC_CODE",
    "AREA_DISTURBED",
    "MATERIAL_TYPE",
    "OTHER_MATERIAL_TYPE",
    "PRODUCTION_AMOUNT",
    "PERMIT_NO",
    "DATE_COVERAGE_BEGAN",
    "MOST_RECENT_REGISTRATION_DT",
    "ISSUE_TO_CN",
    "ISSUE_TO_NAME",
    "RN",
    "RE_NAME",
    "SITE_NAME",
    "COUNTY",
    "TCEQ_REGION",
    "SITE_LATITUDE",
    "SITE_LONGITUDE",
    "SITE_ADDRESS_LABEL",
    "SITE_PHYS_LOC_DESC",
    "SITE_NEAR_CITY_NAME",
    "SITE_NEAR_ZIP",
    "CONTACT FIRST NAME",
    "CONTACT LAST NAME",
    "CONTACT ORGANIZATION",
    "CONTACT_MAILING_ADDRESS",
    "PHONE",
    "PRIMARY_SIC_CODE",
    "AREA_DISTURBED",
    "MATERIAL_TYPE",
    "OTHER_MATERIAL_TYPE",
    "PRODUCTION_AMOUNT",
    "MINE_ID",
    "CURRENT_MINE_NAME",
    "COAL_METAL_IND",
    "CURRENT_MINE_TYPE",
    "CURRENT_MINE_STATUS",
    "CURRENT_STATUS_DT",
    "CURRENT_CONTROLLER_ID",
    "CURRENT_CONTROLLER_NAME",
    "CURRENT_OPERATOR_ID",
    "CURRENT_OPERATOR_NAME",
    "STATE",
    "BOM_STATE_CD",
    "FIPS_CNTY_CD",
    "FIPS_CNTY_NM",
    "CONG_DIST_CD",
    "COMPANY_TYPE",
    "CURRENT_CONTROLLER_BEGIN_DT",
    "DISTRICT",
    "OFFICE_CD",
    "OFFICE_NAME",
    "ASSESS_CTRL_NO",
    "PRIMARY_SIC_CD",
    "PRIMARY_SIC",
    "PRIMARY_SIC_CD_1",
    "PRIMARY_SIC_CD_SFX",
    "SECONDARY_SIC_CD",
    "SECONDARY_SIC",
    "SECONDARY_SIC_CD_1",
    "SECONDARY_SIC_CD_SFX",
    "PRIMARY_CANVASS_CD",
    "PRIMARY_CANVASS",
    "SECONDARY_CANVASS_CD",
    "SECONDARY_CANVASS",
    "CURRENT_103I",
    "CURRENT_103I_DT",
    "PORTABLE_OPERATION",
    "PORTABLE_FIPS_ST_CD",
    "DAYS_PER_WEEK",
    "HOURS_PER_SHIFT",
    "PROD_SHIFTS_PER_DAY",
    "MAINT_SHIFTS_PER_DAY",
    "NO_EMPLOYEES",
    "PART48_TRAINING",
    "LONGITUDE",
    "LATITUDE",
    "AVG_MINE_HEIGHT",
    "MINE_GAS_CATEGORY_CD",
    "METHANE_LIBERATION",
    "NO_PRODUCING_PITS",
    "NO_NONPRODUCING_PITS",
    "NO_TAILING_PONDS",
    "PILLAR_RECOVERY_USED",
    "HIGHWALL_MINER_USED",
    "MULTIPLE_PITS",
    "MINERS_REP_IND",
    "SAFETY_COMMITTEE_IND",
    "MILES_FROM_OFFICE",
    "DIRECTIONS_TO_MINE",
    "NEAREST_TOWN",
    "TABLE_NAME",
    "COLUMN_NAME",
    "DATA_TYPE",
    "DATA_LENGTH",
    "FIELD_DESCRIPTION",
    "Mine ID",
    "Mine Name",
    "Mine Status (Current)",
    "Primary SIC Code",
    "Operator Name (Current)",
    "Operator ID (Current)",
    "Controller Name (Current)",
    "Controller ID (Current)",
    "State Abbreviation",
    "FIPS County Name",
    "Nearest Town",
    "Directions to Mine",
    "Latitude",
    "Longitude",
    "Type Address",
    "Contact Name",
    "Contact Title",
    "Street",
    "City",
    "Zip Code",
    "PO Box",
    "State Name",
    "Phone No.",
    "Fax No.",
    "Email Address",
    "FID",
    "Permit:",
    "Status:",
    "Mine Name:",
    "Mineral Type:",
    "Surface Ownership:",
    "Mineral Ownership:",
    "UTM_E",
    "UTM_N",
    "Company:",
    "GlobalID",
    "CreationDate",
    "Creator",
    "Mine Status",
    "County",
    "Lead",
    "Bond Amount",
    "Email",
    "Lead Phone Number",
    "Updated",
    "DocUsed",
    "OpPhoneNum",
    "Comments",
    "CreationDate.1",
    "Creator.1",
    "EditDate",
    "Editor",
    "CreationDate.2",
    "Creator.2",
    "EditDate.1",
    "Editor.1",
    "x",
    "y",
    "NPDES ID",
    "Unnamed: 1",
    "Facility Name",
    "Permit Name",
    "Unnamed: 4",
    "Unnamed: 5",
    "Permit Status Desc",
    "Unnamed: 7",
    "Location Address",
    "Unnamed: 9",
    "City",
    "Facility Location Info..State Code",
    "Zip",
    "Issue Date",
    "Effective Date",
    "Expiration Date",
    "Primary Facility SIC Code",
    "Latitude in Decimal Degrees",
    "Longitude in Decimal Degrees",
    "State Water Body Name",
    "GPID",
    "PIT_NAME",
    "LOCATION",
    "REL_DESCRIPT",
    "Company/Name",
    "FNAME",
    "LNAME",
    "DELIVERY_ADDRESS",
    "TOWN",
    "STATE",
    "ZIP",
    "TELEPHONE",
    "PIT_STATUS_SEQ",
    "ENDDATE",
    "County",
    "Permit Number",
    "Facility Name",
    "Facility Address",
    "City",
    "Facility Type",
    "Mineral",
    "Name",
    "Status",
    "Type",
    "County",
    "Quad",
    "Grant",
    "Latitude",
    "Longitude",
    "PLSS",
    "Commodities",
    "PermitNumber",
    "MineralOwner",
    "SurfaceOwner",
    "SubmissionFromDate",
    "SubmissionToDate",
    "ApprovalFromDate",
    "ApprovalToDate",
    "RegistrationDate",
    "SignatureDate",
    "StartDate",
    "ClosedDate",
    "Operator",
    "Address",
    "Phone",
    "POC",
    "Email",
    "DrivingDirections",
    "MostRecentAnnualReportYear",
    "DisturbedAcresCurrentYear",
    "DisturbedAcresTotal",
    "ReclaimedAcresCurrentYear",
    "ReclaimedAcresTotal",
    "MineOrPermit",
    "LeaseNumber",
    "County",
    "Township",
    "Range",
    "Section",
    "LegalDescription",
    "CommodityDescription",
    "FirstName",
    "LastName",
    "EntityName",
    "PrimaryAddress",
    "City",
    "State",
    "ZIPCode",
    "First Name",
    "Last Name",
    "Combined Name",
    "Office",
    "Program",
    "Phone\xa0",
    "username",
    "Email",
    "Permit number (ID)",
    "Permittee (Operator)",
    "Site name",
    "Latitude",
    "Longitude",
    "County Name",
    "Range",
    "Section",
    "Township",
    "Qtr-qtr",
    "Qtr",
    "Correspondence(PR) Company Name",
    "Correspondence(PR) Contact First Name",
    "Correspondence(PR) Contact Last Name",
    "Correspondence Telephone Number",
    "Correspondence(PR) Address 1",
    "Correspondence(PR) Address 2",
    "Correspondence(PR) City",
    "Correspondence(PR) State",
    "Correspondence(PR) Zip Code",
    "Commodity",
    "Permit Type",
    "PERMIT #",
    "COMPANY NAME",
    "COUNTY",
    "TOWNSHIP",
    "ISSUANCE DATE",
    "MINERAL(S) MINED",
    "STREET ADDRESS",
    "CITY",
    "STATE",
    "ZIP",
    "PHONE NUMBER",
    "LATITUDE",
    "LONGITUDE",
    "Unnamed: 0",
    "Unnamed: 1",
    "Unnamed: 2",
    "Unnamed: 3",
    "Unnamed: 4",
    "Unnamed: 5",
    "Unnamed: 6",
    "Unnamed: 7",
    "Unnamed: 8",
    "Unnamed: 9",
    "Unnamed: 10",
    "Unnamed: 11",
    "Unnamed: 12",
    "Unnamed: 13",
    "Unnamed: 14",
    "Unnamed: 15",
    "Unnamed: 16",
    "Unnamed: 17",
    "COMPANY",
    "LICENSE",
    "TITLE",
    "FIRST",
    "LAST",
    "STREET",
    "CITY",
    "STATE",
    "ZIP",
    "E-mail",
    "PHONE",
    "FAX",
    "LICSTAT",
    "OBJECTID",
    "Mine_ID",
    "Mine Name",
    "Operation Type",
    "Mine Status",
    "Primary Product",
    "Other Products",
    "Owner",
    "Operator",
    "Lead Agency",
    "Report Year",
    "Acres Disturbed",
    "Reclamation Status",
    "Permit Number",
    "Permit Acres",
    "Financial Assurance Mechanism Total",
    "Financial Assurance Cost Estimate",
    "Latitude",
    "Longitude",
    "x",
    "y",
    "Mine ID",
    "REPORT_YEAR",
    "CONTACT_EMAIL",
    "CONTACT_FIRST",
    "CONTACT_LAST",
    "CONTACT_PHONE",
    "MINE_ADDRESS",
    "MINE_CITY",
    "MINE_STATE",
    "MINE_ZIP",
    "Lead Agency",
    "Permit No",
    "Site Name",
    "Permittee Name",
    "Project Name",
    "Permit Type",
    "Status",
    "Rating",
    "Location",
    "City",
    "County",
    "EFO Name",
    "__Issuance__",
    "_Effective_",
    "__Expiration__",
    "OBJECTID",
    "SITE_ID",
    "SITE_NAME",
    "BOUNDARY",
    "MARKET_RESOURCE",
    "FL_REC_RULE",
    "PERMIT_AGENCY",
    "DATE_ENTERED",
    "DIGITIZER",
    "SORT_GRADE",
    "MINING_BEGAN",
    "MITIGATION_REQD",
    "NONMAN_AREAS",
    "SHEER_WALLS",
    "RuleID",
    "DOCUMENT_LINK",
    "Shape_Length",
    "Shape_Area",
    "CENTROID_X",
    "CENTROID_Y",
    "AI_ID",
    "FACILITY_NAME",
    "ACTIVITY_NO",
    "PERMIT_NO",
    "PHYSICAL_ADDRESS",
    "LATITUDE",
    "LONGITUDE",
    "SIC_CODE",
    "SIC_DESC",
    "MAILING_ADDRESS",
    "WTR_PMT_CONTACT",
    "WPC_PHONE",
    "WPC_EMAIL",
    "ORG_OPERATOR",
    "ORG_OP_PHONE",
    "PERSON_OPERATOR",
    "PERSON_OP_PHONE",
    "PERSON_OP_EMAIL",
    "FACILITY_NAME",
    "LATITUDE",
    "LONGITUDE",
    "Company",
    "City",
    "Contact Person",
    "County",
    "Cur Range",
    "Cur Section",
    "Cur Township",
    "Current Location",
    "Driving Instruction",
    "E-Mail",
    "Elevation",
    "FAX",
    "GPS",
    "lat",
    "Long",
    "Mail Address",
    "Mine•Plant Name",
    "Phone",
    "Product",
    "State",
    "Type",
    "UTM",
    "Zip",
    "County",
    "Company",
    "City",
    "Latitude",
    "Longitude",
    "Mine/Plant Name",
    "Type",
    "Product",
    "Commodity Type",
    "Commodity Family",
    "Asphalt Hot Plant?",
    "Concrete Batch Plant?",
    "NPDES ID",
    "Permit Name",
    "State Facility ID",
    "Mjr",
    "Facility Type Desc",
    "Facility Type Indicator",
    "Permit Type Desc",
    "Permit Status Desc",
    "Issue Date",
    "Effective Date",
    "Expiration Date",
    "Termination Date",
    "Latitude in Decimal Degrees",
    "Longitude in Decimal Degrees",
    "Location Address",
    "City",
    "Facility Location Info..State Code",
    "Zip",
    "County Name",
    "Primary Facility SIC Code",
    "Primary Facility SIC Desc",
    "Permit SIC",
    "Permit SIC Description",
    "FRS HUC Code",
    "HUC Code",
    "State Water Body Name",
    "State Water Body",
    "Total Actual Average Flow (MGD)",
    "Total App. Design Flow (MGD)",
    "FIPS City Code",
    "FIPS County Code",
    "State-Region",
    "Congressional District Number",
    "Legislative District Number",
    "Name",
    "First",
    "Title",
    "Phone",
    "Email",
    "COUNTY        ",
    "COMPANY NAME                  ",
    "MINE NAME/NUMBER    ",
    "PERMIT ",
    "COMMODITY",
    "PERMITTED ACRES",
    "DISTURBED ACRES",
    "ACRES RECLAIMED THIS YR",
    "ORG PERMIT",
    "Name",
    "PermitNumber",
    "FacilityName",
    "Facility Address",
    "Facility SupAddress",
    "City",
    "State",
    "Zip",
    "COMPANY NAME",
    "CONTACT NAME",
    "PHONE",
    "EMAIL",
    "LICENSE #",
    "SITES_NO",
    "SITES_NAME",
    "SITES COUNTY",
    "SITES_Q1",
    "SITES_Q2",
    "SITES_SECTION",
    "SITES_TOWNSHIP",
    "SITES_RANGE",
    "SITES_RANGEDIR",
    "LICENSE TYPE",
    "CALICHE TONNS",
    "CLAY TONNS",
    "GRAVELDREDGE TONNS ",
    "GRAVELSURFACE TONNS ($0)",
    "GYPSUM TONNS  ",
    "LANDFILL TONNS  ",
    "LIMESTONE TONNS ",
    "OTHER TONNS",
    "QUARTZITE TONNS ",
    "ROCK TONNS",
    "SALT TONNS",
    "SANDSURFACE TONNS",
    "SANDDREDGE TONNS",
    "SHALE TONNS",
    "SOIL TONNS",
    "STONE TONNS",
    "TOPSOIL TONNS",
    "VOLCANICASH TONNS",
    "key",
    "Facility ID",
    "ICIS ID",
    "Facility Name",
    "SIC Code",
    "Inspector",
    "Classification",
    "Owner Name",
    "Owner Mailing Address",
    "Facility Physical Address1",
    "Facility Physical Address2",
    "Facility Physical City",
    "Facility Physical State",
    "Facility Physical Zip",
    "Operating",
    "Full PTE",
    "File",
    "Control Region",
    "Responsible Officials",
    "Responsible Officials_Email",
    "Sanctioned",
    "Lat",
    "Long",
    "Pending or Active Permits",
    "Key",
    "Permit ID",
    "Application/Permit",
    "Legal (Prior) ID",
    "Revision Number",
    "Revision Type",
    "Project Name",
    "Project Classifications",
    "Permit Type",
    "Facility ID",
    "Facility Owner",
    "Facility Name",
    "Received Date",
    "Received Complete Date",
    "Issue Date",
    "Total Elapsed Days",
    "Hold Days",
    "Net Elapsed Days",
    "Hold Ongoing",
    "Effective Date",
    "Expire Date",
    "Permit Status",
    "Engineer",
    "Begin Work",
    "Draft Deliver to Super",
    "Start Public Notice",
    "End Public Notice",
    "Final Deliver to Super",
    "Transmit to EPA",
    "Facility Inspector",
    "Phase Code",
    "Sanctioned?",
    "CWPName",
    "SourceID",
    "CWPStreet",
    "CWPCity",
    "CWPState",
    "RegistryID",
    "CWPSICCodes",
    "CWPNAICSCodes",
    "FacLat",
    "FacLong",
    "CWPFacilityTypeCode",
    "FacMapFlg",
    "DFR URL",
    "Site ID",
    "Name",
    "Manager",
    "Classification",
    "Status",
    "Permit Status",
    "Region",
    "Permit",
    "Site / Facility",
    "City",
    "Owner / Operator",
    "Date Issued",
    "Primary SIC/NAICS code",
    "Seconday SIC/NAICS code",
    "GPS Latitude",
    "GPS Longitude",
    "Facility Physical Address",
    "Facility Physical Description",
    "Borough (or similar governemtn subdivision)",
    "Phone number",
    "email address",
    "Company Name",
    "Quarry/Mine Name",
    "Legal Description",
    "County",
    "Permit No",
    "Product",
    "Contact Company",
    "Contact Address",
    "Contact Name",
    "Phone Number",
    "Cell",
    "Category",
    "Permit Number",
    "Company",
    "Company Address",
    "Local Address",
    "Contact Name",
    "Contact Number",
    "Email Address",
    "Type of Operation",
    "COUNTY",
    "CREATED_BY",
    "CREATED_DA",
    "GLOBALID",
    "HISTORICPE",
    "LATITUDE",
    "LONGITUDE",
    "MODIFIED_B",
    "MODIFIED_D",
    "OBJECTID",
    "OPENCUTNUM",
    "OPERATORCO",
    "OPERATORNA",
    "PENDING_AC",
    "PREAPP_ACT",
    "REF_COMPLA",
    "RELEASE_IN",
    "RELEASE_RE",
    "RETRIEVED",
    "SITENAME",
    "SITESTATUS",
    "Permit Code",
    "Description",
    "5,000CY &/or 1-acre Limit per 12-month Period",
    "NO Extraction Limit",
    "Reclamation Plan Required",
    "Reclamation Security Required",
    "NOTE: DOGAMI permits are renewed annually on a rotating schedule. Surface mining renewals include reported production for the previous 12-month period. For example, sites that renew in December 2018 report production from December 2017 through November 2018.  Therefore our final 2017 production numbers are not available until after all the 2018 renewals have been processed. This usually occurs by mid-spring. If the entry in the state-wide row is labeled incomplete, that means our records show that not all renewals for that year have been processed and the total production numbers are not yet finalized.",
    "PermitID",
    "Permit Type",
    "Status",
    "Site Name",
    "Permittee",
    "Department",
    "Address1",
    "Address2",
    "City",
    "State",
    "Zip",
    "Country",
    "Landowner",
    "Commodity",
    "County",
    "TRS TL",
    "Latitude",
    "Longitude",
    "Site Address",
    "DEQ Permit",
    "DEQ Status",
    "DEQ_FileNo",
    "GoogleMapsLink",
    "Permit#",
    "Permit Year",
    "Amendment/Expansion",
    "Status",
    "PermiteeName",
    "CountyCode",
    "CountyName",
    "Phone",
    "Fax",
    "Email",
    "Address1",
    "Address2",
    "City",
    "State",
    "Zip",
    "PermitType",
    "FeesPaid",
    "GRFees",
    "Credit",
    "ApplicationDate",
    "IssuanceDate",
    "ExpirationDate",
    "EffectiveDate",
    "OperatorNames",
    "Inspector",
    "AreaNumber",
    "Comments",
    "KeyIdImHead",
    "PERMIT_NUMBER",
    "Permittee_Bus_Name",
    "LOCATION_NAME",
    "FIPS_COUNTY_DESC",
    "REGION_NAME",
    "River_Basin_Name",
    "ORIG_ISSUE_DATE",
    "EXPIRATION_DATE",
    "Select Contact Person",
    "Select Addr, City, State, Zip",
    "Phone",
    "ORIGINAL_APP_RECEIVED_DATE",
    "HEARING_DATE",
    "DATE_DENIED",
    "PERMIT_REVISION_DATE",
    "RELEASE_DATE",
    "MINE_STATUS",
    "COMMODITY_CODE",
    "TOTAL_ACRES_PERMITTED",
    "BONDED_ACRES",
    "BOND_TYPE_CODE",
    "ARR_RECEIVED_DATE",
    "BOND_AMOUNT",
    "QUADRANGLE_NAME",
    "LATITUDE_MEASURE",
    "LONGITUDE_MEASURE",
    "CALENDAR_YEAR",
    "NEW_ACRES_AFFECTED_TOTAL",
    "NEW_ACRES_RECLAIMED",
    "ACRES_CURRENT_TOTAL",
    "LAST_UPDATE_DATE",
    "INSPECTED_BY",
    "LAST_NOD_DATE",
    "LAST_NOV_DATE",
    "Last_Inspection_Date",
    "NEXT_SCHEDULED_INSPECTION_DATE",
    "Unnamed: 0",
    "PERMIT #",
    "COMPANY NAME & ADDRESS",
    "#",
    "CASH",
    "SURETY ",
    "Unnamed: 6",
    "NEGOT. ",
    "Unnamed: 8",
    "BOND",
    "PERMIT ",
    "ACREAGE",
    "COUNTY",
    "SECTION",
    "TOWN-",
    "RANGE",
    "ACCESS TO MINE SITES",
    "Material 1 Code",
    "Permit ID",
    "Mine Name",
    "Owner Name",
    "Contacts",
    "Permitted Acres",
    "Site County",
    "Longitude",
    "Latitude",
    "Ute North",
    "Ute East",
    "Map ID",
    "Billing Address",
    "Billing CSZ",
    "Company EMail",
    "I-002131",
    "CALHOUN MINE",
    "HAIR & SONS INC",
    "CALHOUN",
    "SAND",
    "SANDCLAY",
    "-80.88516638",
    33.63659272,
    "no record",
    "SicPrimary",
    "Desc1",
    "TownCode",
    "Premise",
    "EMIT Reporting Period",
    "SiteName",
    "AddressLine1",
    "AddressLine2",
    "City",
    "ZipCode",
    "Zip4",
    "AFINDash",
    "PmtNbr",
    "AFIN",
    "LINK",
    "FacName",
    "Decimal Latitude",
    "Decimal Longitude",
    "FacSiteCity",
    "FacCounty",
    "FacCountyName",
    "FacPrimarySICCode",
    "FacPrimarySICDesc",
    "FacSecondarySICCode",
    "FacSecondarySICDesc",
    "FacTertiarySICCode",
    "FacTertiarySICDesc",
    "FacPrimaryNAICSCode",
    "FacPrimaryNAICSDesc",
    "FacSecondaryNAICSCode",
    "FacSecondaryNAICSDesc",
    "FacTertiaryNAICSCode",
    "FacTertiaryNAICSDesc",
    "PermitteeNameAddress",
    "PmtMedia",
    "MediaDesc",
    "PmtType",
    "PmtTypeDesc",
    "PmtStatus",
    "PmtStatusDesc",
    "MediaPlusPmtTypeCode",
    "PmtPDFOnline",
    "PmtPDFOnlineDIR",
    "Registration Number",
    "Regulated Entity Reference Number ",
    "Facility Type",
    "Facility Name",
    "Address",
    "City",
    "State",
    "Zip",
    "County",
    "TCEQ Region",
    "Registration Date",
    "Phone",
    "PERMIT_NO",
    "DATE_COVERAGE_BEGAN",
    "CN",
    "PERMITTEE_NAME",
    "RN",
    "SITE_NAME",
    "COUNTY",
    "TCEQ_REGION",
    "SITE_ADDRESS",
    "SITE_PHYS_LOC_DESC",
    "SITE_NEAR_CITY_NAME",
    "SITE_NEAR_ZIP",
    "PRIMARY_SIC_CODE",
    "SECONDARY_SIC_CODE",
    "SECTOR",
    "ACTIVITY_CODE",
    "AI",
    "RN",
    "AUTH TYPE",
    "APPROVAL DATE",
    "ORIGINAL APPROVAL DATE",
    "EXPIRATION DATE",
    "AUTH STATUS",
    "TPDES/STATE",
    "EPA ID",
    "EPA FAC CLASS",
    "CN",
    "PERMITTEE NAME(S)",
    "PERMITTEE ADDRESS(S)",
    "FACILITY COUNTY",
    "REGION",
    "SECONDARY COUNTY",
    "SECONDARY REGION",
    "AI SITE NAME",
    "SITE LOCATION",
    "LATTITUDE",
    "LONGITUDE",
    "PERMIT AUTHORITY",
    "COMPLIANCE AUTHORITY",
    "FACILITY OPERATIONAL STATUS",
    "FACILITY DISPOSAL METHOD",
    "PRETREATMENT FACILITY DESIGNATION",
    "FACILITY TOXIC RATING",
    "FACILITY AVG DESIGN FLOW",
    "LOCATED IN COASTAL ZONE",
    "INSTITUTE OF HIGHER LEARNING",
    "BIO-ENERGY FACILITY",
    "TREATMENT COMPONENT",
    "PRIMARY SIC CODE",
    "SECONDARY SIC CODE",
    "PRIMARY NAICS CODE",
    "SECONDARY NAICS CODE",
    "SEGMENT",
    "BASIN",
    "ANIMAL TYPE & HEAD COUNT",
    "FACILITY CHARACTERISTICS ID",
    "PERMIT_NO",
    "DATE_COVERAGE_BEGAN",
    "CN",
    "PERMITTEE_NAME",
    "RN",
    "SITE_NAME",
    "COUNTY",
    "TCEQ_REGION",
    "SITE_ADDRESS",
    "SITE_PHYS_LOC_DESC",
    "SITE_NEAR_CITY_NAME",
    "SITE_NEAR_ZIP",
    "PRIMARY_SIC_CODE",
    "SECONDARY_SIC_CODE",
    "AREA_DISTURBED",
    "SEGMENT_NUMBER",
    "RECEIVING_WATER_BODY",
    "PERMIT_NO",
    "DATE_COVERAGE_BEGAN",
    "CN",
    "PERMITTEE_NAME",
    "RN",
    "SITE_NAME",
    "COUNTY",
    "TCEQ_REGION",
    "SITE_ADDRESS",
    "SITE_PHYS_LOC_DESC",
    "SITE_NEAR_CITY_NAME",
    "SITE_NEAR_ZIP",
    "PRIMARY_SIC_CODE",
    "SECONDARY_SIC_CODE",
    "SECTOR",
    "ACTIVITY_CODE",
    "Supplier",
    "Code",
    "Permit",
    "Link",
    "Program",
    "Site Name",
    "Additional ID",
    "Physical Type",
    "Legal Status",
    "Legal Status Date",
    "Physical Site Status",
    "RN",
    "County",
    "Region",
    "Phys Addr Line 1",
    "Phys Addr Line 2",
    "Phys Addr City",
    "Phys Addr State",
    "Phys Addr Zip",
    "Phys Addr Zip+4",
    "Near Phys Loc Txt",
    "Near Phys Loc City",
    "Near Phys Loc State",
    "Near Phys Loc Zip",
    "Latitude",
    "Longitude",
    "PERMIT_NO",
    "DATE_COVERAGE_BEGAN",
    "MOST_RECENT_REGISTRATION_DT",
    "ISSUE_TO_CN",
    "ISSUE_TO_NAME",
    "RN",
    "RE_NAME",
    "SITE_NAME",
    "COUNTY",
    "TCEQ_REGION",
    "SITE_LATITUDE",
    "SITE_LONGITUDE",
    "SITE_ADDRESS_LABEL",
    "SITE_PHYS_LOC_DESC",
    "SITE_NEAR_CITY_NAME",
    "SITE_NEAR_ZIP",
    "CONTACT FIRST NAME",
    "CONTACT LAST NAME",
    "CONTACT ORGANIZATION",
    "CONTACT_MAILING_ADDRESS",
    "PHONE",
    "no record",
    "PRIMARY_SIC_CODE",
    "AREA_DISTURBED",
    "MATERIAL_TYPE",
    "OTHER_MATERIAL_TYPE",
    "PRODUCTION_AMOUNT",
    "PERMIT_NO",
    "DATE_COVERAGE_BEGAN",
    "MOST_RECENT_REGISTRATION_DT",
    "ISSUE_TO_CN",
    "ISSUE_TO_NAME",
    "RN",
    "RE_NAME",
    "SITE_NAME",
    "COUNTY",
    "TCEQ_REGION",
    "SITE_LATITUDE",
    "SITE_LONGITUDE",
    "SITE_ADDRESS_LABEL",
    "SITE_PHYS_LOC_DESC",
    "SITE_NEAR_CITY_NAME",
    "SITE_NEAR_ZIP",
    "CONTACT FIRST NAME",
    "CONTACT LAST NAME",
    "CONTACT ORGANIZATION",
    "CONTACT_MAILING_ADDRESS",
    "PHONE",
    "PRIMARY_SIC_CODE",
    "AREA_DISTURBED",
    "MATERIAL_TYPE",
    "OTHER_MATERIAL_TYPE",
    "PRODUCTION_AMOUNT",
    "MINE_ID",
    "CURRENT_MINE_NAME",
    "COAL_METAL_IND",
    "CURRENT_MINE_TYPE",
    "CURRENT_MINE_STATUS",
    "CURRENT_STATUS_DT",
    "CURRENT_CONTROLLER_ID",
    "CURRENT_CONTROLLER_NAME",
    "CURRENT_OPERATOR_ID",
    "CURRENT_OPERATOR_NAME",
    "STATE",
    "BOM_STATE_CD",
    "FIPS_CNTY_CD",
    "FIPS_CNTY_NM",
    "CONG_DIST_CD",
    "COMPANY_TYPE",
    "CURRENT_CONTROLLER_BEGIN_DT",
    "DISTRICT",
    "OFFICE_CD",
    "OFFICE_NAME",
    "ASSESS_CTRL_NO",
    "PRIMARY_SIC_CD",
    "PRIMARY_SIC",
    "PRIMARY_SIC_CD_1",
    "PRIMARY_SIC_CD_SFX",
    "SECONDARY_SIC_CD",
    "SECONDARY_SIC",
    "SECONDARY_SIC_CD_1",
    "SECONDARY_SIC_CD_SFX",
    "PRIMARY_CANVASS_CD",
    "PRIMARY_CANVASS",
    "SECONDARY_CANVASS_CD",
    "SECONDARY_CANVASS",
    "CURRENT_103I",
    "CURRENT_103I_DT",
    "PORTABLE_OPERATION",
    "PORTABLE_FIPS_ST_CD",
    "DAYS_PER_WEEK",
    "HOURS_PER_SHIFT",
    "PROD_SHIFTS_PER_DAY",
    "MAINT_SHIFTS_PER_DAY",
    "NO_EMPLOYEES",
    "PART48_TRAINING",
    "LONGITUDE",
    "LATITUDE",
    "AVG_MINE_HEIGHT",
    "MINE_GAS_CATEGORY_CD",
    "METHANE_LIBERATION",
    "NO_PRODUCING_PITS",
    "NO_NONPRODUCING_PITS",
    "NO_TAILING_PONDS",
    "PILLAR_RECOVERY_USED",
    "HIGHWALL_MINER_USED",
    "MULTIPLE_PITS",
    "MINERS_REP_IND",
    "SAFETY_COMMITTEE_IND",
    "MILES_FROM_OFFICE",
    "DIRECTIONS_TO_MINE",
    "NEAREST_TOWN",
    "TABLE_NAME",
    "COLUMN_NAME",
    "DATA_TYPE",
    "DATA_LENGTH",
    "FIELD_DESCRIPTION",
    "Mine ID",
    "Mine Name",
    "Mine Status (Current)",
    "Primary SIC Code",
    "Operator Name (Current)",
    "Operator ID (Current)",
    "Controller Name (Current)",
    "Controller ID (Current)",
    "State Abbreviation",
    "FIPS County Name",
    "Nearest Town",
    "Directions to Mine",
    "Latitude",
    "Longitude",
    "Type Address",
    "Contact Name",
    "Contact Title",
    "Street",
    "City",
    "Zip Code",
    "PO Box",
    "State Name",
    "Phone No.",
    "Fax No.",
    "Email Address",
    "FID",
    "Permit:",
    "Status:",
    "Mine Name:",
    "Mineral Type:",
    "Surface Ownership:",
    "Mineral Ownership:",
    "UTM_E",
    "UTM_N",
    "Company:",
    "GlobalID",
    "CreationDate",
    "Creator",
    "Mine Status",
    "County",
    "Lead",
    "Bond Amount",
    "Email",
    "Lead Phone Number",
    "Updated",
    "DocUsed",
    "OpPhoneNum",
    "Comments",
    "CreationDate.1",
    "Creator.1",
    "EditDate",
    "Editor",
    "CreationDate.2",
    "Creator.2",
    "EditDate.1",
    "Editor.1",
    "x",
    "y",
    "NPDES ID",
    "Unnamed: 1",
    "Facility Name",
    "Permit Name",
    "Unnamed: 4",
    "Unnamed: 5",
    "Permit Status Desc",
    "Unnamed: 7",
    "Location Address",
    "Unnamed: 9",
    "City",
    "Facility Location Info..State Code",
    "Zip",
    "Issue Date",
    "Effective Date",
    "Expiration Date",
    "Primary Facility SIC Code",
    "Latitude in Decimal Degrees",
    "Longitude in Decimal Degrees",
    "State Water Body Name",
    "GPID",
    "PIT_NAME",
    "LOCATION",
    "REL_DESCRIPT",
    "Company/Name",
    "FNAME",
    "LNAME",
    "DELIVERY_ADDRESS",
    "TOWN",
    "STATE",
    "ZIP",
    "TELEPHONE",
    "PIT_STATUS_SEQ",
    "ENDDATE",
    "County",
    "Permit Number",
    "Facility Name",
    "Facility Address",
    "City",
    "Facility Type",
    "Mineral",
    "Name",
    "Status",
    "Type",
    "County",
    "Quad",
    "Grant",
    "Latitude",
    "Longitude",
    "PLSS",
    "Commodities",
    "PermitNumber",
    "MineralOwner",
    "SurfaceOwner",
    "SubmissionFromDate",
    "SubmissionToDate",
    "ApprovalFromDate",
    "ApprovalToDate",
    "RegistrationDate",
    "SignatureDate",
    "StartDate",
    "ClosedDate",
    "Operator",
    "Address",
    "Phone",
    "POC",
    "Email",
    "DrivingDirections",
    "MostRecentAnnualReportYear",
    "DisturbedAcresCurrentYear",
    "DisturbedAcresTotal",
    "ReclaimedAcresCurrentYear",
    "ReclaimedAcresTotal",
    "MineOrPermit",
]

