mine_schema = {
    "site_name": ["mine_name", "current_mine_name", "mineplant_name"],
    "mine_type": ["current_mine_type"],
    "longitude": ["long", "lng", "gps longitude", "gps long", "gps lng"],
    "latitude": ["lat", "gps latitude", "gps lat"],
    "state": ["phys_addr_state", "state_abbreviation"],
    "city": ["phys_addr_city"],
    "street_address": ["phys_addr_line_1", "street", "current_location"],
    "zip": ["phys_addr_zip", "zip_code"],
    "fips_county_code": ["fips_cnty_cd"],
    "fips_county": ["county", "fips_cnty_nm", "fips_county_name"],
    "physical_status": [
        "physical_site_status",
        "current_mine_status",
        "mine_status_current",
    ],
    "legal_status": [],
    "primary_sic": ["product"],
    "primary_sic_code": ["primary_sic_cd"],
    "secondary_sic": [],
    "secondary_sic_code": ["secondary_sic_cd"],
    "primary_canvass": [],
    "primary_canvass_code": ["primary_canvass_cd"],
    "secondary_canvass_code": ["secondary_canvass_cd"],
    "secondary_canvass": [],
    "controller": ["current_controller_name", "controller_name_current", "company"],
    "operator": ["current_operator_name", "operator_name_current"],
    "directions_to_mine": ["near_phys_loc_txt", "driving_instruction"],
    "nearest_town": ["near_phys_loc_city"],
    "physical_mail_address": ["mail_address"],
    "email": ["email_address"],
    "phone": ["phone_no", "phone_no."],
    "office_address": [],
    "website_URL": [],
    "contact_name": ["contact_person"],
    "keep_it_as_it_is": [
        "program",
        "physical_type",
        "legal_status_date",
        "region",
        "phys_addr_line_2",
        "phys_addr_zip4",
        "near_phys_loc_zip",
        "current_status_dt",
        "district",
        "office_name",
        "no_producing_pits",
        "miles_from_office",
        "contact_title",
        "po_box",
        "cur_range",
        "cur_section",
        "cur_township",
        "fax",
        "gps",
    ],
    "dropped_cols": [
        "additional_id",
        "rn",
        "near_phys_loc_state",
        "mine_id",
        "coal_metal_ind",
        "current_controller_id",
        "current_operator_id",
        "bom_state_cd",
        "cong_dist_cd",
        "company_type",
        "current_controller_begin_dt",
        "office_cd",
        "assess_ctrl_no",
        "primary_sic_cd_1",
        "primary_sic_cd_sfx",
        "secondary_sic_cd_1",
        "secondary_sic_cd_sfx",
        "current_103i",
        "current_103i_dt",
        "portable_operation",
        "portable_fips_st_cd",
        "days_per_week",
        "hours_per_shift",
        "prod_shifts_per_day",
        "maint_shifts_per_day",
        "no_employees",
        "part48_training",
        "avg_mine_height",
        "mine_gas_category_cd",
        "methane_liberation",
        "no_nonproducing_pits",
        "no_tailing_ponds",
        "pillar_recovery_used",
        "highwall_miner_used",
        "multiple_pits",
        "miners_rep_ind",
        "safety_committee_ind",
        "index",
        "operator_id_current",
        "controller_id_current",
        "type_address",
        "state_name",
        "elevation",
        "utm",
    ],
}

