colnames = [
    "#",
    "5,000CY &/or 1-acre Limit per 12-month Period",
    "ACCESS TO MINE SITES",
    "ACREAGE",
    "ACRES RECLAIMED THIS YR",
    "ACRES_CURRENT_TOTAL",
    "ACTIVITY_CODE",
    "ACTIVITY_NO",
    "AFIN",
    "AFINDash",
    "AI",
    "AI SITE NAME",
    "AI_ID",
    "APPROVAL DATE",
    "AREA_DISTURBED",
    "ARR_RECEIVED_DATE",
    "ASSESS_CTRL_NO",
    "AUTH STATUS",
    "AUTH TYPE",
    "AVG_MINE_HEIGHT",
    "Acres Disturbed",
    "Additional ID",
    "Address",
    "Address1",
    "Address2",
    "AddressLine1",
    "AddressLine2",
    "Amendment/Expansion",
    "Application/Permit",
    "ApplicationDate",
    "ApprovalFromDate",
    "AreaNumber",
    "Asphalt Hot Plant?",
    "BASIN",
    "BOM_STATE_CD",
    "BOND",
    "BONDED_ACRES",
    "BOND_AMOUNT",
    "BOND_TYPE_CODE",
    "BOUNDARY",
    "BUSINESS_NAME",
    "Begin Work",
    "Billing Address",
    "Billing CSZ",
    "Bond Amount",
    "CALENDAR_YEAR",
    "CALICHE TONNS",
    "CASH",
    "CENTROID_X",
    "CENTROID_Y",
    "CITY",
    "CLAY TONNS",
    "CN",
    "COAL_METAL_IND",
    "COLUMN_NAME",
    "COMMODITY",
    "COMMODITY_CODE",
    "COMPANY",
    "COMPANY NAME",
    "COMPANY NAME                  ",
    "COMPANY NAME & ADDRESS",
    "COMPANY_TYPE",
    "CONG_DIST_CD",
    "CONTACT FIRST NAME",
    "CONTACT LAST NAME",
    "CONTACT NAME",
    "CONTACT ORGANIZATION",
    "CONTACT_EMAIL",
    "CONTACT_FIRST",
    "CONTACT_LAST",
    "CONTACT_MAILING_ADDRESS",
    "CONTACT_PHONE",
    "CONTACT_TITLE",
    "COUNTRY",
    "COUNTY",
    "COUNTY        ",
    "CREATED_BY",
    "CREATED_DA",
    "CURRENT_103I",
    "CURRENT_103I_DT",
    "CURRENT_CONTROLLER_BEGIN_DT",
    "CURRENT_CONTROLLER_ID",
    "CURRENT_CONTROLLER_NAME",
    "CURRENT_MINE_NAME",
    "CURRENT_MINE_STATUS",
    "CURRENT_MINE_TYPE",
    "CURRENT_OPERATOR_ID",
    "CURRENT_OPERATOR_NAME",
    "CURRENT_STATUS_DT",
    "CWPCity",
    "CWPFacilityTypeCode",
    "CWPNAICSCodes",
    "CWPName",
    "CWPSICCodes",
    "CWPState",
    "CWPStreet",
    "Category",
    "Cell",
    "City",
    "Classification",
    "ClosedDate",
    "Code",
    "Combined Name",
    "Comments",
    "Commodities",
    "Commodity",
    "Commodity Family",
    "Commodity Type",
    "CommodityDescription",
    "Company",
    "Company Address",
    "Company EMail",
    "Company Name",
    "Company/Name",
    "Company:",
    "Concrete Batch Plant?",
    "Congressional District Number",
    "Contact Address",
    "Contact Company",
    "Contact Name",
    "Contact Number",
    "Contact Person",
    "Contact Title",
    "Contacts",
    "Control Region",
    "Controller ID (Current)",
    "Controller Name (Current)",
    "Correspondence Telephone Number",
    "Correspondence(PR) Address 1",
    "Correspondence(PR) Address 2",
    "Correspondence(PR) City",
    "Correspondence(PR) Company Name",
    "Correspondence(PR) Contact First Name",
    "Correspondence(PR) Contact Last Name",
    "Correspondence(PR) State",
    "Correspondence(PR) Zip Code",
    "Country",
    "County",
    "County Name",
    "CountyCode",
    "CountyName",
    "CreationDate",
    "CreationDate.1",
    "CreationDate.2",
    "Creator",
    "Creator.1",
    "Creator.2",
    "Credit",
    "Cur Range",
    "Cur Section",
    "Cur Township",
    "Current Location",
    "DATA_LENGTH",
    "DATA_TYPE",
    "DATE_COVERAGE_BEGAN",
    "DATE_DENIED",
    "DATE_ENTERED",
    "DAYS_PER_WEEK",
    "DELIVERY_ADDRESS",
    "DEQ Permit",
    "DEQ Status",
    "DEQ_FileNo",
    "DFR URL",
    "DIGITIZER",
    "DIRECTIONS_TO_MINE",
    "DIST OFFICE",
    "DISTRICT",
    "DISTURBED ACRES",
    "DNR Region",
    "DOCUMENT_LINK",
    "Date Issued",
    "Decimal Latitude",
    "Decimal Longitude",
    "Department",
    "Desc1",
    "Description",
    "Directions to Mine",
    "DisturbedAcresCurrentYear",
    "DisturbedAcresTotal",
    "DocUsed",
    "Draft Deliver to Super",
    "Driving Instruction",
    "DrivingDirections",
    "E-Mail",
    "E-mail",
    "EFO Name",
    "EMAIL",
    "EMIT Reporting Period",
    "ENDDATE",
    "EPA FAC CLASS",
    "EPA ID",
    "EXPIRATION DATE",
    "EXPIRATION_DATE",
    "EditDate",
    "EditDate.1",
    "Editor",
    "Editor.1",
    "Effective Date",
    "EffectiveDate",
    "Elevation",
    "Email",
    "Email Address",
    "End Public Notice",
    "Engineer",
    "EntityName",
    "Expiration Date",
    "ExpirationDate",
    "Expire Date",
    "FACILITY CHARACTERISTICS ID",
    "FACILITY COUNTY",
    "FACILITY DISPOSAL METHOD",
    "FACILITY TOXIC RATING",
    "FACILITY_NAME",
    "FAX",
    "FID",
    "FIELD_DESCRIPTION",
    "FIN",
    "FINALIZED DATE",
    "FIPS City Code",
    "FIPS County Code",
    "FIPS County Name",
    "FIPS_CNTY_CD",
    "FIPS_CNTY_NM",
    "FIPS_COUNTY_DESC",
    "FIPS_STATE_CD",
    "FIRST",
    "FL_REC_RULE",
    "FNAME",
    "FRS HUC Code",
    "FacCounty",
    "FacCountyName",
    "FacLat",
    "FacLong",
    "FacMapFlg",
    "FacName",
    "FacPrimaryNAICSCode",
    "FacPrimaryNAICSDesc",
    "FacPrimarySICCode",
    "FacPrimarySICDesc",
    "FacSecondarySICCode",
    "FacSecondarySICDesc",
    "FacSiteCity",
    "FacTertiarySICCode",
    "Facility Address",
    "Facility ID",
    "Facility Inspector",
    "Facility Location Info..State Code",
    "Facility Name",
    "Facility Owner",
    "Facility Physical Address1",
    "Facility Physical Address2",
    "Facility Physical City",
    "Facility Physical State",
    "Facility Physical Zip",
    "Facility SupAddress",
    "Facility Type",
    "Facility Type Desc",
    "Facility Type Indicator",
    "FacilityName",
    "Fax",
    "Fax No.",
    "FeesPaid",
    "File",
    "Final Deliver to Super",
    "Financial Assurance Cost Estimate",
    "Financial Assurance Mechanism Total",
    "First",
    "First Name",
    "FirstName",
    "Full PTE",
    "GLOBALID",
    "GPID",
    "GPS",
    "GRAVELDREDGE TONNS ",
    "GRAVELSURFACE TONNS ($0)",
    "GRFees",
    "GYPSUM TONNS  ",
    "GlobalID",
    "GoogleMapsLink",
    "Grant",
    "HEARING_DATE",
    "HIGHWALL_MINER_USED",
    "HISTORICPE",
    "HOURS_PER_SHIFT",
    "HUC Code",
    "Hold Days",
    "Hold Ongoing",
    "ICIS ID",
    "INSPECTED_BY",
    "INSPECTOR",
    "INSTITUTE OF HIGHER LEARNING",
    "ISSUANCE DATE",
    "ISSUE_TO_CN",
    "ISSUE_TO_NAME",
    "Inspector",
    "IssuanceDate",
    "Issue Date",
    "Key",
    "KeyIdImHead",
    "LANDFILL TONNS  ",
    "LAST",
    "LAST_NOD_DATE",
    "LAST_NOV_DATE",
    "LAST_UPDATE_DATE",
    "LATITUDE",
    "LATITUDE_MEASURE",
    "LATTITUDE",
    "LICENSE",
    "LICENSE #",
    "LICENSE TYPE",
    "LICSTAT",
    "LIMESTONE TONNS ",
    "LINK",
    "LNAME",
    "LOCATED IN COASTAL ZONE",
    "LOCATION",
    "LOCATION_NAME",
    "LONGITUDE",
    "LONGITUDE_MEASURE",
    "Landowner",
    "Last Name",
    "LastName",
    "Last_Inspection_Date",
    "Lat",
    "Latitude",
    "Latitude in Decimal Degrees",
    "Lead",
    "Lead Agency",
    "Lead Phone Number",
    "LeaseNumber",
    "Legal (Prior) ID",
    "Legal Description",
    "Legal Status",
    "Legal Status Date",
    "LegalDescription",
    "Legislative District Number",
    "Link",
    "Local Address",
    "Location",
    "Location Address",
    "Long",
    "Longitude",
    "Longitude in Decimal Degrees",
    "MAILING_ADDRESS",
    "MAINT_SHIFTS_PER_DAY",
    "MARKET_RESOURCE",
    "MATERIAL_TYPE",
    "MCD",
    "METHANE_LIBERATION",
    "MILES_FROM_OFFICE",
    "MINE NAME/NUMBER    ",
    "MINERAL(S) MINED",
    "MINERS_REP_IND",
    "MINE_ADDRESS",
    "MINE_CITY",
    "MINE_GAS_CATEGORY_CD",
    "MINE_ID",
    "MINE_NAME",
    "MINE_STATE",
    "MINE_STATUS",
    "MINE_STATUS_DT",
    "MINE_TYPE_CD",
    "MINE_ZIP",
    "MINING_BEGAN",
    "MITIGATION_REQD",
    "MODIFIED_D",
    "MOST_RECENT_REGISTRATION_DT",
    "MULTIPLE_PITS",
    "Mail Address",
    "Manager",
    "Map ID",
    "Material 1 Code",
    "MediaDesc",
    "MediaPlusPmtTypeCode",
    "Mine ID",
    "Mine Name",
    "Mine Name:",
    "Mine Status",
    "Mine Status (Current)",
    "Mine/Plant Name",
    "MineOrPermit",
    "Mine_ID",
    "Mineral",
    "Mineral Group",
    "Mineral Ownership:",
    "Mineral Type",
    "Mineral Type:",
    "MineralOwner",
    "Mine•Plant Name",
    "Mjr",
    "MostRecentAnnualReportYear",
    "NEAREST_TOWN",
    "NEGOT. ",
    "NEW_ACRES_AFFECTED_TOTAL",
    "NEW_ACRES_RECLAIMED",
    "NEXT_SCHEDULED_INSPECTION_DATE",
    "NO Extraction Limit",
    "NONMAN_AREAS",
    "NOTE: DOGAMI permits are renewed annually on a rotating schedule. Surface mining renewals include reported production for the previous 12-month period. For example, sites that renew in December 2018 report production from December 2017 through November 2018.  Therefore our final 2017 production numbers are not available until after all the 2018 renewals have been processed. This usually occurs by mid-spring. If the entry in the state-wide row is labeled incomplete, that means our records show that not all renewals for that year have been processed and the total production numbers are not yet finalized.",
    "NO_EMPLOYEES",
    "NO_NONPRODUCING_PITS",
    "NO_PRODUCING_PITS",
    "NO_TAILING_PONDS",
    "NPDES ID",
    "Name",
    "Near Phys Loc City",
    "Near Phys Loc State",
    "Near Phys Loc Txt",
    "Near Phys Loc Zip",
    "Nearest Town",
    "Net Elapsed Days",
    "OBJECTID",
    "OFFICE_CD",
    "OFFICE_NAME",
    "OPENCUTNUM",
    "OPERATORCO",
    "OPERATORNA",
    "ORG PERMIT",
    "ORG_OPERATOR",
    "ORG_OP_PHONE",
    "ORIGINAL APPROVAL DATE",
    "ORIGINAL_APP_RECEIVED_DATE",
    "ORIG_ISSUE_DATE",
    "OTHER_MATERIAL_TYPE",
    "Office",
    "OpPhoneNum",
    "Operating",
    "Operation Type",
    "Operator",
    "Operator ID (Current)",
    "Operator Name (Current)",
    "OperatorNames",
    "Other Products",
    "Owner",
    "Owner / Operator",
    "Owner Mailing Address",
    "Owner Name",
    "PART48_TRAINING",
    "PENDING_AC",
    "PERMIT ",
    "PERMIT #",
    "PERMIT AUTHORITY",
    "PERMITTED ACRES",
    "PERMITTEE ADDRESS(S)",
    "PERMITTEE NAME(S)",
    "PERMITTEE_NAME",
    "PERMIT_AGENCY",
    "PERMIT_NO",
    "PERMIT_NUMBER",
    "PERMIT_REVISION_DATE",
    "PERSON_OPERATOR",
    "PERSON_OP_EMAIL",
    "PERSON_OP_PHONE",
    "PHONE",
    "PHONE NUMBER",
    "PHYSICAL_ADDRESS",
    "PILLAR_RECOVERY_USED",
    "PIT_NAME",
    "PIT_STATUS_SEQ",
    "PLSS",
    "PO Box",
    "POC",
    "PORTABLE_FIPS_ST_CD",
    "PORTABLE_OPERATION",
    "POSTAL_CD",
    "PO_BOX",
    "PREAPP_ACT",
    "PRIMARY NAICS CODE",
    "PRIMARY SIC CODE",
    "PRIMARY_CANVASS",
    "PRIMARY_CANVASS_CD",
    "PRIMARY_SIC",
    "PRIMARY_SIC_CD",
    "PRIMARY_SIC_CD_1",
    "PRIMARY_SIC_CD_SFX",
    "PRIMARY_SIC_CODE",
    "PRODUCTION_AMOUNT",
    "PROD_SHIFTS_PER_DAY",
    "PROVINCE",
    "Pending or Active Permits",
    "Permit",
    "Permit Acres",
    "Permit Code",
    "Permit ID",
    "Permit Name",
    "Permit No",
    "Permit Number",
    "Permit SIC",
    "Permit SIC Description",
    "Permit Status",
    "Permit Status Desc",
    "Permit Type",
    "Permit Type Desc",
    "Permit Year",
    "Permit number (ID)",
    "Permit#",
    "Permit:",
    "PermitID",
    "PermitNumber",
    "PermitType",
    "PermiteeName",
    "Permitted Acres",
    "Permittee",
    "Permittee (Operator)",
    "Permittee Name",
    "PermitteeNameAddress",
    "Permittee_Bus_Name",
    "Phase Code",
    "Phone",
    "Phone No.",
    "Phone Number",
    "Phone\xa0",
    "Phys Addr City",
    "Phys Addr Line 1",
    "Phys Addr Line 2",
    "Phys Addr State",
    "Phys Addr Zip",
    "Phys Addr Zip+4",
    "Physical Site Status",
    "Physical Type",
    "PmtMedia",
    "PmtNbr",
    "PmtPDFOnline",
    "PmtPDFOnlineDIR",
    "PmtStatus",
    "PmtStatusDesc",
    "PmtType",
    "PmtTypeDesc",
    "Premise",
    "Primary Facility SIC Code",
    "Primary Facility SIC Desc",
    "Primary Product",
    "Primary SIC Code",
    "Primary SIC/NAICS code",
    "PrimaryAddress",
    "Product",
    "Program",
    "Project Classifications",
    "Project Name",
    "QUADRANGLE_NAME",
    "QUARTZITE TONNS ",
    "Qtr",
    "Qtr-qtr",
    "Quad",
    "Quarry/Mine Name",
    "RANGE",
    "RECEIVING_WATER_BODY",
    "REF_COMPLA",
    "REGION",
    "REGION_NAME",
    "RELEASE_DATE",
    "RELEASE_IN",
    "RELEASE_RE",
    "REL_DESCRIPT",
    "REPORT_YEAR",
    "RETRIEVED",
    "RE_NAME",
    "RN",
    "ROCK TONNS",
    "Range",
    "Rating",
    "Received Complete Date",
    "Received Date",
    "ReclaimedAcresCurrentYear",
    "ReclaimedAcresTotal",
    "Reclamation Plan Required",
    "Reclamation Security Required",
    "Reclamation Status",
    "Region",
    "Registration Date",
    "Registration Number",
    "RegistrationDate",
    "RegistryID",
    "Regulated Entity Reference Number ",
    "Report Year",
    "Responsible Officials",
    "Responsible Officials_Email",
    "Revision Number",
    "Revision Type",
    "River_Basin_Name",
    "RuleID",
    "SAFETY_COMMITTEE_IND",
    "SALT TONNS",
    "SANDDREDGE TONNS",
    "SANDSURFACE TONNS",
    "SECONDARY COUNTY",
    "SECONDARY NAICS CODE",
    "SECONDARY SIC CODE",
    "SECONDARY_CANVASS",
    "SECONDARY_CANVASS_CD",
    "SECONDARY_SIC",
    "SECONDARY_SIC_CD",
    "SECONDARY_SIC_CD_1",
    "SECONDARY_SIC_CD_SFX",
    "SECONDARY_SIC_CODE",
    "SECTION",
    "SECTOR",
    "SEGMENT",
    "SEGMENT_NUMBER",
    "SHALE TONNS",
    "SHEER_WALLS",
    "SIC Code",
    "SIC_CODE",
    "SIC_DESC",
    "SITE LOCATION",
    "SITENAME",
    "SITES COUNTY",
    "SITESTATUS",
    "SITES_NAME",
    "SITES_NO",
    "SITES_Q1",
    "SITES_Q2",
    "SITES_RANGE",
    "SITES_RANGEDIR",
    "SITES_SECTION",
    "SITES_TOWNSHIP",
    "SITE_ADDRESS",
    "SITE_ADDRESS_LABEL",
    "SITE_ID",
    "SITE_LATITUDE",
    "SITE_LONGITUDE",
    "SITE_NAME",
    "SITE_NEAR_CITY_NAME",
    "SITE_NEAR_ZIP",
    "SITE_PHYS_LOC_DESC",
    "SOIL TONNS",
    "SORT_GRADE",
    "STATE",
    "STATE_ABBR",
    "STATUS",
    "STONE TONNS",
    "STREET",
    "STREET ADDRESS",
    "SURETY ",
    "Sanctioned",
    "Sanctioned?",
    "Section",
    "Select Addr, City, State, Zip",
    "Select Contact Person",
    "Shape_Area",
    "Shape_Length",
    "SicPrimary",
    "SignatureDate",
    "Site / Facility",
    "Site Address",
    "Site County",
    "Site ID",
    "Site Name",
    "Site name",
    "SiteName",
    "SourceID",
    "Start Public Notice",
    "StartDate",
    "State",
    "State Abbreviation",
    "State Facility ID",
    "State Name",
    "State Water Body",
    "State Water Body Name",
    "State-Region",
    "Status",
    "Status:",
    "Street",
    "SubmissionFromDate",
    "Supplier",
    "Surface Ownership:",
    "SurfaceOwner",
    "TABLE_NAME",
    "TCEQ Region",
    "TCEQ_REGION",
    "TELEPHONE",
    "TITLE",
    "TOPSOIL TONNS",
    "TOTAL_ACRES_PERMITTED",
    "TOWN",
    "TOWN-",
    "TOWNSHIP",
    "TPDES/STATE",
    "TREATMENT COMPONENT",
    "TRS TL",
    "Termination Date",
    "Title",
    "Total Actual Average Flow (MGD)",
    "Total App. Design Flow (MGD)",
    "Total Elapsed Days",
    "TownCode",
    "Township",
    "Transmit to EPA",
    "Type",
    "Type Address",
    "Type of Operation",
    "UTM",
    "UTM_E",
    "UTM_N",
    "Unnamed: 0",
    "Unnamed: 1",
    "Unnamed: 6",
    "Unnamed: 8",
    "Updated",
    "Ute East",
    "Ute North",
    "VOLCANICASH TONNS",
    "WPC_EMAIL",
    "WPC_PHONE",
    "WTR_PMT_CONTACT",
    "ZIP",
    "ZIPCode",
    "ZIP_CD",
    "Zip",
    "Zip Code",
    "_Effective_",
    "__Expiration__",
    "__Issuance__",
    "key",
    "lat",
    "no record",
    "username",
    "x",
    "y",
]

