all_columns = [
    "MINE_ID",
    "CURRENT_MINE_NAME",
    "COAL_METAL_IND",
    "CURRENT_MINE_TYPE",
    "CURRENT_MINE_STATUS",
    "CURRENT_STATUS_DT",
    "CURRENT_CONTROLLER_ID",
    "CURRENT_CONTROLLER_NAME",
    "CURRENT_OPERATOR_ID",
    "CURRENT_OPERATOR_NAME",
    "STATE",
    "BOM_STATE_CD",
    "FIPS_CNTY_CD",
    "FIPS_CNTY_NM",
    "CURRENT_CONTROLLER_BEGIN_DT",
    "PRIMARY_SIC_CD",
    "PRIMARY_SIC",
    "PRIMARY_SIC_CD_1",
    "PRIMARY_SIC_CD_SFX",
    "SECONDARY_SIC_CD",
    "SECONDARY_SIC",
    "SECONDARY_SIC_CD_1",
    "SECONDARY_SIC_CD_SFX",
    "PRIMARY_CANVASS_CD",
    "PRIMARY_CANVASS",
    "SECONDARY_CANVASS_CD",
    "SECONDARY_CANVASS",
    "PORTABLE_OPERATION",
    "PORTABLE_FIPS_ST_CD",
    "LONGITUDE",
    "LATITUDE",
    "DIRECTIONS_TO_MINE",
    "NEAREST_TOWN",
]

target_columns = [
    "MINE_ID",
    "CURRENT_MINE_NAME",
    "COAL_METAL_IND",
    "CURRENT_MINE_TYPE",
    "CURRENT_MINE_STATUS",
    "CURRENT_STATUS_DT",
    "CURRENT_CONTROLLER_ID",
    "CURRENT_CONTROLLER_NAME",
    "CURRENT_OPERATOR_ID",
    "CURRENT_OPERATOR_NAME",
    "STATE",
    "BOM_STATE_CD",
    "FIPS_CNTY_CD",
    "FIPS_CNTY_NM",
    "CURRENT_CONTROLLER_BEGIN_DT",
    "PRIMARY_SIC_CD",
    "PRIMARY_SIC",
    "PRIMARY_SIC_CD_1",
    "PRIMARY_SIC_CD_SFX",
    "SECONDARY_SIC_CD",
    "SECONDARY_SIC",
    "SECONDARY_SIC_CD_1",
    "SECONDARY_SIC_CD_SFX",
    "PRIMARY_CANVASS_CD",
    "PRIMARY_CANVASS",
    "SECONDARY_CANVASS_CD",
    "SECONDARY_CANVASS",
    "PORTABLE_OPERATION",
    "PORTABLE_FIPS_ST_CD",
    "LONGITUDE",
    "LATITUDE",
    "DIRECTIONS_TO_MINE",
    "NEAREST_TOWN",
]

all_materials = [
    "Agate",
    "Alumina",
    "Aluminum Ore-Bauxite",
    "Amethyst",
    "Antimony Ore",
    "Aplite",
    "Asbestos",
    "Barite Barium Ore",
    "Bentonite",
    "Beryl-Beryllium Ore",
    "Boron Minerals",
    "Brucite",
    "Cement",
    "Chem. and Fertil. Mnls. NEC",
    "Chromite Chromium Ore",
    "Clay, Ceramic, Refractory Mnls.",
    "Coal (Anthracite)",
    "Coal (Bituminous)",
    "Coal (Lignite)",
    "Cobalt Ore",
    "Colloidal Phosphates",
    "Columbium Tantalum Ore",
    "Common Clays NEC",
    "Common Shale",
    "Construction Sand and Gravel",
    "Copper Ore NEC",
    "Cristobalite, Ground",
    "Crushed, Broken Basalt",
    "Crushed, Broken Granite",
    "Crushed, Broken Limestone NEC",
    "Crushed, Broken Marble",
    "Crushed, Broken Mica",
    "Crushed, Broken Quartzite",
    "Crushed, Broken Sandstone",
    "Crushed, Broken Slate",
    "Crushed, Broken Stone NEC",
    "Crushed, Broken Traprock",
    "Cryolite",
    "Diatomaceous Earth (Diatomite)",
    "Dimension Basalt",
    "Dimension Granite",
    "Dimension Limestone",
    "Dimension Marble",
    "Dimension Mica",
    "Dimension Quartzite",
    "Dimension Sandstone",
    "Dimension Slate",
    "Dimension Stone NEC",
    "Dimension Traprock",
    "Emerald",
    "Feldspar",
    "Fire Clay",
    "Fluorspar",
    "Fullers Earth",
    "Garnet",
    "Gemstones",
    "Gilsonite",
    "Gold Ore",
    "Graphite",
    "Ground Silica",
    "Gypsum",
    "Industrial Inorg. Chemicals",
    "Iron Ore",
    "Kaolin and Ball Clay",
    "Kyanite",
    "Lead",
    "Lead-Zinc Ore",
    "Leonardite",
    "Lime",
    "Lithium Minerals",
    "Magnesite",
    "Magnetite",
    "Manganese Ore",
    "Mercury Ore",
    "Mica",
    "Misc. Metal Ore NEC",
    "Misc. Nonmetallic Mnls. NEC",
    "Molybdenum Ore",
    "Nickel Ore",
    "Oil Mining",
    "Oil Sand",
    "Oil Shale",
    "Olivine",
    "Perlite",
    "Phosphate Rock",
    "Pigment Minerals",
    "Platinum Group Ore",
    "Potash",
    "Potash, Soda, Borate Mnls. NEC",
    "Potassium Compounds",
    "Pumice",
    "Pyrites",
    "Pyrophyllite",
    "Quartz, Crystal",
    "Quartz, Ground",
    "Rare Earths Ore",
    "Salt",
    "Salt, Brine Evaporated",
    "Sand, Common",
    "Sand, Industrial NEC",
    "Sapphire",
    "Shell",
    "Silver Ore",
    "Soapstone, Crushed Dimension",
    "Sodium Compounds",
    "Sulfur",
    "Talc",
    "Tin Ore",
    "Titanium Ore",
    "Tripoli",
    "Trona",
    "Tungsten Ore",
    "Turquoise",
    "Uranium Ore",
    "Uranium-Vanadium Ore",
    "Vanadium Ore",
    "Vermiculite",
    "Wollastonite",
    "Zeolites",
    "Zinc",
    "Zirconium Ore",
]
target_materials = [
    "Cement",
    "Clay, Ceramic, Refractory Mnls.",
    "Common Clays NEC",
    "Common Shale",
    "Construction Sand and Gravel",
    "Crushed, Broken Basalt",
    "Crushed, Broken Granite",
    "Crushed, Broken Limestone NEC",
    "Crushed, Broken Marble",
    "Crushed, Broken Mica",
    "Crushed, Broken Quartzite",
    "Crushed, Broken Sandstone",
    "Crushed, Broken Slate",
    "Crushed, Broken Stone NEC",
    "Crushed, Broken Traprock",
    "Dimension Basalt",
    "Dimension Granite",
    "Dimension Limestone",
    "Dimension Marble",
    "Dimension Mica",
    "Dimension Quartzite",
    "Dimension Sandstone",
    "Dimension Slate",
    "Dimension Stone NEC",
    "Dimension Traprock",
    "Lime",
    "Nonmetal",
    "Sand, Common",
    "Sand, Industrial NEC",
]

all_statuses = [
    "Active",
    "Abandoned",
    "Abandoned and Sealed",
    "NonProducing",
    "Temporarily Idled",
    "Intermittent",
    "New Mine",
]
target_statuses = ["Active", "Intermittent", "New Mine"]

all_canvasses = ["Stone", "Nonmetal", "Coal", "Metal", "SandAndGravel"]
target_canvasses = ["Stone", "Nonmetal", "SandAndGravel"]

all_types = ["Surface", "Underground", "Facility"]
target_types = ["Surface", "Facility"]

# TODO: should organise this into a class

